services:
  - type: web
    name: la-nostra-libreria
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: libreria-data
      mountPath: /data
      sizeGB: 1